server:
  port: 8080

spring:
  datasource:

    url: jdbc:mysql://localhost:3306/securetrack
    username: root
    password: 12345

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
