server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://securetracks.mysql.database.azure.com:3306/securetracks
    username: securetracks
    password: Ngo098867915712nn@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
